Disable GL for npymath
This is required so that VS2017 can be used for C extensions to link against an
older numpy built with VS2015

Exact error:
fatal error C1047: '\path\to\npymath.lib' was created with an older
compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed

xref: https://github.com/statsmodels/statsmodels/issues/4011
xref: https://github.com/numpy/numpy/pull/9965